version: "3.7"

services: 
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: "projectapi"